services:
  web-dev:
    build:
      context: .
      dockerfile: "docker/api/dev/Dockerfile"
    env_file:
      - "config/.env.dev"
    depends_on:
      "mysql-dev":
        condition: service_healthy
    profiles: ["dev"]
    ports:
      - "80:80"
    volumes:
      - "./:/app"
  mysql-dev:
    image: "mysql"
    env_file:
      - "config/.env.dev"
    profiles: ["dev"]
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "${MYSQL_USER:-root}", "-p${MYSQL_PASSWORD}", "ping"]
      interval: 10s
      timeout: 10s
      retries: 30
  web:
    image: "webdevops/php-apache:8.2"
    env_file:
      - "config/.env"
    depends_on:
      - mysql
    profiles: ["prod"]
    ports:
      - "80:80"
  mysql:
    image: "mysql"
    env_file:
      - "config/.env"
    profiles: ["prod"]
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"

